### ISSUE TITLE
I can't not preview the map

### ISSUE THREAD

**Issue by hhkaos** [jgrayson-apl/VectorBasemapStyleEditor#2] opened 2016-05-30 04:53 UTC
Hi @jgrayson-apl, I'm trying to use the app but I'm getting some errors trying to load the map at the bottom left. These are the messages that appears in the console.

```
init.js:199 TypeError: Cannot read property 'remove' of undefined(…) "TypeError: Cannot read property 'remove' of undefined
    at q._unsetMap (http://js.arcgis.com/3.16/init.js:919:134)
    at f.removeLayer (http://js.arcgis.com/3.16/init.js:383:460)
    at f.removeAllLayers (http://js.arcgis.com/3.16/init.js:384:208)
    at .<anonymous> (http://maps.esri.com/AGSJS_Demos/templates/VectorBasemapStyleEditor/js/main.js:900:20)
    at http://js.arcgis.com/3.16/init.js:167:296
    at k (http://js.arcgis.com/3.16/init.js:189:431)
    at q (http://js.arcgis.com/3.16/init.js:189:357)
    at resolve (http://js.arcgis.com/3.16/init.js:191:441)
    at .<anonymous> (http://maps.esri.com/AGSJS_Demos/templates/VectorBasemapStyleEditor/js/main.js:846:20)
    at http://js.arcgis.com/3.16/init.js:167:296
    ----------------------------------------
    rejected at a (http://js.arcgis.com/3.16/init.js:190:337)
    at k (http://js.arcgis.com/3.16/init.js:190:89)
    at q (http://js.arcgis.com/3.16/init.js:189:357)
    at resolve (http://js.arcgis.com/3.16/init.js:191:441)
    at .<anonymous> (http://maps.esri.com/AGSJS_Demos/templates/VectorBasemapStyleEditor/js/main.js:846:20)
    at http://js.arcgis.com/3.16/init.js:167:296
    at c (http://js.arcgis.com/3.16/init.js:66:221)
    at d (http://js.arcgis.com/3.16/init.js:66:10)
    at resolve.callback (http://js.arcgis.com/3.16/init.js:67:350)
    at c (http://js.arcgis.com/3.16/init.js:66:436)
    ----------------------------------------
Error
    at then.b.then (http://js.arcgis.com/3.16/init.js:192:253)
    at declare.itemSelected (http://maps.esri.com/AGSJS_Demos/templates/VectorBasemapStyleEditor/js/main.js:860:31)
    at .<anonymous> (http://maps.esri.com/AGSJS_Demos/templates/VectorBasemapStyleEditor/js/main.js:293:14)
    at HTMLDivElement.<anonymous> (http://js.arcgis.com/3.16/init.js:167:296)
    at Function.k.emit (http://js.arcgis.com/3.16/init.js:211:269)
    at w._fireSelectionEvent (http://js.arcgis.com/3.16/dgrid/Selection.js:13:103)
    at w._fireSelectionEvents (http://js.arcgis.com/3.16/dgrid/Selection.js:13:236)
    at w.select (http://js.arcgis.com/3.16/dgrid/Selection.js:15:274)
    at w._singleSelectionHandler (http://js.arcgis.com/3.16/dgrid/Selection.js:8:484)
    at w._handleSelect (http://js.arcgis.com/3.16/dgrid/Selection.js:8:279)"
2
init.js:360 Uncaught TypeError: Cannot read property 'getWidth' of undefined
2
main.js:418 Uncaught TypeError: Cannot read property 'data' of undefined
4
init.js:360 Uncaught TypeError: Cannot read property 'getWidth' of undefined
```

Any ideas? This Tuesday we have a Developer Summit and I was planning to show it, maybe I can do a quickfix.

Thanks in advance!

**Comment by jgrayson-apl** [comment] 2016-05-30 18:21
Raul, I can't reproduce this issue.  Please note that I just pushed a update that should help with one of the small issues mentioned above. However, that issue should NOT cause major problems and the app should still allow you to preview the layer, make changes, and update the item.  Since I can not reproducethe 'I can't not preview the map' issue, could you please try again and let me know if you still encounter problems?  Please try with other items to see if the issue is specific to a single item.  If you can still reproduce, I will need the exact steps taken so I can reproduce the error over here.  If possible, please share the agol id of the problematic item and we can try to make a copy to further test.

**Comment by WJVierbergen** [comment] 2016-09-08 14:49
Hi jgrayson-apl,

I ran into the same issue. I have the issue with any item, even when I copy it in the app from an Esri Basemap.

While using an Esri Basemap, the app makes the following GET request:
http://basemaps.arcgis.com/arcgis/rest/services/World_Basemap/VectorTileServer/resources/styles/http:/www.arcgis.com/sharing/rest/content/items/3e3099d7302f4d99bc6f916dcc07ed59/resources/sprites/sprite.json
Response is 403. 
I think that one of the following requests should have been made?:
http://basemaps.arcgis.com/arcgis/rest/services/World_Basemap/VectorTileServer/resources/sprites/sprite.json
OR
http://www.arcgis.com/sharing/rest/content/items/3e3099d7302f4d99bc6f916dcc07ed59/resources/sprites/sprite.json

When using my own Vector Basemaps, the behavior is similar, but I get a 404 instead of a 403:
http://tiles.arcgis.com/tiles/emS4w7iyWEQiulAb/arcgis/rest/services/Test_08_09/VectorTileServer/resources/styles/http:/tiles.arcgis.com/tiles/emS4w7iyWEQiulAb/arcgis/rest/services/Test_08_09/VectorTileServer/resources/sprites/sprite.json?token=8h7NBA....
Response is 404.

I tried different browsers and even another machine...

Thanks in advance!

**Comment by jgrayson-apl** [comment] 2016-09-08 15:48
WJVierbergen, 
    I can't reproduce this issue.  
    Did you register your version of the apps with your org?  Did you update the "oauthappid" in defaults.js?  Have you changed the code in other ways?  Is your version of this application available publicly?  
    Please note that this application is designed to ONLY works with Esri basemap items. The code relies on information provided by the JS API about the logged in user to generate the urls to the glyphs and sprites; see the section commented with "UPDATE STYLE TO USE USE GLYPHS AND SPRITES FROM COPY BASEMAP ITEM". You can debug into this part of the code and view details about how those urls are created.

**Comment by WJVierbergen** [comment] 2016-09-08 15:59
Hi John,

Thanks for your reply. I did not download the app to host it myself, I'm just using this one: http://maps.esri.com/AGSJS_Demos/templates/VectorBasemapStyleEditor/index.html

**Comment by jgrayson-apl** [comment] 2016-09-08 16:11
Willem,
	That is just my internal reference app that goes through many changes as we adapt to new versions of the JS API; it's currently not configured to be used externally as we're in the process of making some critical updates.  This application is designed as a template web application registered in an organization.  If you'd like a stable version, it's recommended to please download the code and deploy to your own web server.  

 * Copy your application to a web accessible location
 * Create a new item in your org to your version of this application
 * Register the new application item and make note of the App ID
 * In /config/default.js change the oauthappid to the above App ID

	This will allow you to sign into your own org with the appropriate credentials and the correct user information will be used when trying to copy the Esri basemap items.

**Comment by WJVierbergen** [comment] 2016-09-09 11:38
Thanks John,

I'll try to follow your steps to deploy it on our webserver.
However, I also just noticed that the map preview on http://maps.esri.com/AGSJS_Demos/templates/VectorBasemapStyleEditor/index.html works now! Thanks! I'll keep in mind that this one is not stable and deploy it on our server anyway.

Thanks again!

**Comment by hhkaos** [comment] 2016-09-10 12:30
Thank's John, sorry I didn't see this email before.

It's work perfectly with other items but I've checked that I can not preview [this item](https://www.arcgis.com/home/item.html?id=11f6905de3974550820d41b1ed5eceb6). 

Another suggestion: It would be also nice that when you click on "Pick color" it forces the "Find by color" tab to be selected (in case the user would be in the "Style layers"). I forgot that and I though that the "Pick color" action was broken... ^_^''. I think this can be done adding this:

```js
var tabPanel = registry.byId("main-center-pane");
var tabs = tabPanel.getChildren();
tabPanel.selectChild(tabs[1]);
```

After [line 1036 in main.js](https://github.com/jgrayson-apl/VectorBasemapStyleEditor/blob/master/js/main.js#L1036)

By the way, my local version is not working now because **StyleUpdate.js** is not in [js/Operations/](https://github.com/jgrayson-apl/VectorBasemapStyleEditor/tree/master/js/Operations) folder as main.js requests [in line 61](https://github.com/jgrayson-apl/VectorBasemapStyleEditor/blob/master/js/main.js#L61)

Cheers!

**Comment by jgrayson-apl** [comment] 2016-09-10 20:14
Raul,

- Unfortunately, I can't reproduce this issue. I made a copy or the item and I can preview and update my copy of your item.
- the "Find by Color" tool is going away with the next major update to this application, so I will re-consider your enhancement request if/when we bring back this functionality at a future release.
- I just pushed an update that removes the invalid reference mentioned.

It seems like this entry has been used to point out various problems which we can no longer reproduce.  We're going to close this issue, but please submit new ones as you encounter them and we'll check them out.  Please note that we'll be making a major update in a few weeks, so please wait for version 0.2.0 and then test again.  Thank you.

**Closed by jgrayson-apl** 2016-09-10 20:14 UTC

**Comment by hhkaos** [comment] 2016-09-11 15:21
Perfect John, thanks :)
